### ISSUE TITLE
suggestion: use direnv?

### ISSUE THREAD

**Issue by hydrargyrum** [simonw/click-app#1]
[direnv](https://direnv.net/) is a tool to have env variables set when your shell enters some directory, and possibly create a venv.

This part could be replaced:

```
cd {{ cookiecutter.hyphenated }}
python -mvenv venv
source venv/bin/activate
```

Let me explain, for example, `{{cookiecutter.hyphenated}}` template directory could contain a `.envrc` with the following content:
```
layout python3
```

When `direnv` is properly installed on your system, you must mark your shiny new repository as trusted (because `direnv` may allow arbitrary content to be run, every `.envrc` must be marked manually as trusted):

```
direnv allow <path to repo>
```

So a venv will be created automatically in `<repo>/.direnv/python-<version>`, and it will be activated every time you `cd` somewhere in the generated repository.

**Comment by simonw** [comment]
I like `direnv`, but I don't want to assume that anyone using this template will be familiar with it - so I'm going to leave it out of the template.
